const pizzas=[
  {
    "id": 1,
    "name": "Margherita",
    "description": "Classic cheese pizza with tomato sauce",
    "category": "Veg",
    "basePrice": 199,
    "sizes": { "small": 199, "medium": 299, "large": 399 },
    "crusts": ["Regular", "Thin"],
    "toppings": ["Extra Cheese", "Olives", "Jalapenos"],
    "image": "margherita.jpg",
    "available": true
  },
  {
    "id": 2,
    "name": "Farmhouse",
    "description": "Loaded with fresh veggies and cheese",
    "category": "Veg",
    "basePrice": 249,
    "sizes": { "small": 249, "medium": 349, "large": 449 },
    "crusts": ["Regular", "Cheese Burst"],
    "toppings": ["Mushroom", "Capsicum", "Onion"],
    "image": "farmhouse.jpg",
    "available": true
  },
  {
    "id": 3,
    "name": "Peppy Paneer",
    "description": "Paneer with capsicum and red paprika",
    "category": "Veg",
    "basePrice": 269,
    "sizes": { "small": 269, "medium": 369, "large": 469 },
    "crusts": ["Regular", "Thin"],
    "toppings": ["Extra Cheese", "Jalapenos"],
    "image": "peppy_paneer.jpg",
    "available": true
  },
  {
    "id": 4,
    "name": "Veggie Delight",
    "description": "Crunchy veggies and mozzarella",
    "category": "Veg",
    "basePrice": 229,
    "sizes": { "small": 229, "medium": 329, "large": 429 },
    "crusts": ["Thin", "Regular"],
    "toppings": ["Onion", "Capsicum", "Olives"],
    "image": "veggie_delight.jpg",
    "available": true
  },
  {
    "id": 5,
    "name": "Mexican Green Wave",
    "description": "Mexican herbs with spicy veggies",
    "category": "Veg",
    "basePrice": 279,
    "sizes": { "small": 279, "medium": 379, "large": 479 },
    "crusts": ["Regular", "Cheese Burst"],
    "toppings": ["Jalapenos", "Olives"],
    "image": "mexican_green_wave.jpg",
    "available": true
  },
  {
    "id": 6,
    "name": "Pepperoni",
    "description": "Pepperoni with mozzarella cheese",
    "category": "Non-Veg",
    "basePrice": 299,
    "sizes": { "small": 299, "medium": 399, "large": 499 },
    "crusts": ["Thin", "Cheese Burst"],
    "toppings": ["Extra Cheese", "Olives"],
    "image": "pepperoni.jpg",
    "available": true
  },
  {
    "id": 7,
    "name": "BBQ Chicken",
    "description": "BBQ chicken with smoky flavor",
    "category": "Non-Veg",
    "basePrice": 329,
    "sizes": { "small": 329, "medium": 429, "large": 529 },
    "crusts": ["Regular", "Cheese Burst"],
    "toppings": ["Onion", "Extra Cheese"],
    "image": "bbq_chicken.jpg",
    "available": true
  },
  {
    "id": 8,
    "name": "Chicken Tikka",
    "description": "Spicy chicken tikka with onions",
    "category": "Non-Veg",
    "basePrice": 319,
    "sizes": { "small": 319, "medium": 419, "large": 519 },
    "crusts": ["Regular", "Thin"],
    "toppings": ["Onion", "Extra Cheese"],
    "image": "chicken_tikka.jpg",
    "available": true
  },
  {
    "id": 9,
    "name": "Peri Peri Chicken",
    "description": "Peri peri chicken with fiery taste",
    "category": "Non-Veg",
    "basePrice": 339,
    "sizes": { "small": 339, "medium": 439, "large": 539 },
    "crusts": ["Thin", "Cheese Burst"],
    "toppings": ["Jalapenos", "Extra Cheese"],
    "image": "peri_peri_chicken.jpg",
    "available": true
  },
  {
    "id": 10,
    "name": "Cheese Burst Special",
    "description": "Extra cheesy indulgence",
    "category": "Veg",
    "basePrice": 289,
    "sizes": { "small": 289, "medium": 389, "large": 489 },
    "crusts": ["Cheese Burst"],
    "toppings": ["Extra Cheese"],
    "image": "cheese_burst_special.jpg",
    "available": true
  },
  {
    "id": 11,
    "name": "Four Cheese",
    "description": "Blend of mozzarella, cheddar, parmesan, gouda",
    "category": "Veg",
    "basePrice": 309,
    "sizes": { "small": 309, "medium": 409, "large": 509 },
    "crusts": ["Thin", "Regular"],
    "toppings": ["Extra Cheese"],
    "image": "four_cheese.jpg",
    "available": true
  },
  {
    "id": 12,
    "name": "Chicken Sausage",
    "description": "Chicken sausage with herbs",
    "category": "Non-Veg",
    "basePrice": 319,
    "sizes": { "small": 319, "medium": 419, "large": 519 },
    "crusts": ["Regular", "Thin"],
    "toppings": ["Olives", "Extra Cheese"],
    "image": "chicken_sausage.jpg",
    "available": true
  },
  {
    "id": 13,
    "name": "Spicy Paneer",
    "description": "Hot paneer with spicy seasoning",
    "category": "Veg",
    "basePrice": 279,
    "sizes": { "small": 279, "medium": 379, "large": 479 },
    "crusts": ["Thin", "Regular"],
    "toppings": ["Jalapenos", "Extra Cheese"],
    "image": "spicy_paneer.jpg",
    "available": true
  },
  {
    "id": 14,
    "name": "Mushroom Magic",
    "description": "Mushrooms with creamy cheese",
    "category": "Veg",
    "basePrice": 259,
    "sizes": { "small": 259, "medium": 359, "large": 459 },
    "crusts": ["Regular", "Thin"],
    "toppings": ["Mushroom", "Extra Cheese"],
    "image": "mushroom_magic.jpg",
    "available": true
  },
  {
    "id": 15,
    "name": "Ultimate Meat Feast",
    "description": "Loaded with chicken, sausage, and pepperoni",
    "category": "Non-Veg",
    "basePrice": 369,
    "sizes": { "small": 369, "medium": 469, "large": 569 },
    "crusts": ["Cheese Burst", "Thin"],
    "toppings": ["Extra Cheese"],
    "image": "ultimate_meat_feast.jpg",
    "available": true
  }
]
export default pizzas;